credentials:
  usernames:
    admin1:
      email: admin@example.com
      name: Admin User
      password: '$2b$12$Q7mtbHaK605TF.pv67TvH.XBWVJEqU1MRFs8JKaSDrGAK3ChRmXvS'
      roles:
        - admin
    eng1:
      email: eng1@example.com
      name: Engineer User
      password: '$2b$12$upW00B3FXeQG2z40Q4t68.IrUPFChE3hd.oKVdV0MwK/49gmDQxDW'
      roles:
        - engineer
    analyst1:
      email: analyst@example.com
      name: Analyst User
      password: '$2b$12$MQ1Eq26BMQ1SBjzoyKc6S.zqZ/0/EoXRDYkSW12RgDYK3twtd93su'
      roles:
        - analyst

cookie:
  expiry_days: 7
  key: some_secure_cookie_key
  name: streamlit_app_auth
